from digrafica import Digrafica

d = Digrafica()
d.leer_digrafica("digrafica.txt")
print(d)
print("---------------------")
d.eliminar_nodo("c")
print(d)
print(d.eliminar_arco("a","b"))
print(d.eliminar_arco("e","b"))
print(d.obtener_numero_nodos())
print(d.obtener_numero_arcos())
print(d.obtener_grado("a", "positivo"))
print(d.obtener_grado("a", "negativo"))
print(d.obtener_grado("d", "positivo"))
print(d.obtener_grado("d", "negativo"))
print("------------------------------------")
print("------------------------------------")
d.vaciar_nodo("f")
print(d.obtener_numero_arcos())
print(d.obtener_numero_nodos())
print(d)
print(d.obtener_numero_arcos())
print(d.obtener_numero_nodos())
print(d.obtener_grado("e", "positivo"))
print(d.obtener_grado("e", "negativo"))
